name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/setup-stack@v1
    - name: Install dependencies
      run: |
        stack setup
    - name: Build
      run: |
        stack build
    - name: Run tests
      run: stack test
